### ISSUE TITLE
IC8 I2C-EEPROM Part Number?

### ISSUE THREAD

**Issue by huajijam** [ataradov/usb-sniffer#3]
Not found in readme and sch

**Comment by huajijam** [comment]
found in https://github.com/ataradov/usb-sniffer/discussions/2

using 24lc128 for mine now

**Comment by ataradov** [comment]
I've updated the schematic with the EEPROM part name and a full part name for the FPGA. 
I've also added note that FPGA speed grade 4 will not work, as it is too slow.
