### ISSUE TITLE
usb_sniffer_linux failed with latest linux wireshark 4.2.5

### ISSUE THREAD

**Issue by mosquito520** [ataradov/usb-sniffer#35]
Hi

I've using linux mint 21.2 (based on Ubuntu Jammy)
When I install system package wireshark 3.6.2.2
I can select USB sniffer on wireshark list interface, and I can receive data
not able to decode, but I can find different package size during enumeration

Due to Wireshark 3.x does not support usb decode
so I've using PPA to install latest wireshark 4.2.5
when I upgrade Wireshark to 4.2.5, I'm not able to select USB sniffer on wireshark anymore.

Does usb_sniffer_linux test with 4.2.5 before?

Thanks

**Comment by ataradov** [comment]
Note that you may need to create this directory if it already does not exists.

**Comment by mosquito520** [comment]
> At some point Wireshark updated the location for the extcap plugins. The resent versions seem to use "~/.local/lib/wireshark/extcap". I have updated the Makefile accordingly.
> 
> In order to find out what this path is on your system, look in Help -> About Wireshark -> Folders -> Personal Extcap path.

Thanks for reply, I'll verify it tomorrow:)

**Comment by mosquito520** [comment]
Hi Alex
Thanks for reply !
I've confirm it work when change to "~/.local/lib/wireshark/extcap"
Also
> In order to find out what this path is on your system, look in Help -> About Wireshark -> Folders -> Personal Extcap path."
is clear !

But I'll suggest https://github.com/ataradov/usb-sniffer?tab=readme-ov-file#installation
Maybe update this description would be nice

Thanks for your effort! :smile:

**Comment by ataradov** [comment]
Fixed the readme.
